version: "3"

volumes:
  blog_local_postgres_data: {}
  blog_local_postgres_data_backups: {}
  django_media: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    image: blog_local_django
    container_name: blog_local_django
    depends_on:
      - postgres
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.django
      - ./.envs/.postgres
    expose:
      - 8000
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/postgres/Dockerfile
    image: blog_production_postgres
    container_name: blog_local_postgres
    volumes:
      - blog_local_postgres_data:/var/lib/postgresql/data
      - blog_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.postgres

  nginx:
    build:
      context: .
      dockerfile: ./compose/nginx/Dockerfile
    image: django_nginx
    container_name: django_nginx
    restart: always
    depends_on:
      - django
    ports:
      - "80:80"
    volumes:
      - django_media:/usr/src/app

  redis:
    image: redis:latest
    container_name: blog_local_redis
    ports:
      - "6379:6379"

  celery_worker:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    image: django_celery_worker
    command: /start-celeryworker
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.django
      - ./.envs/.postgres
    depends_on:
      - redis
      - postgres

  celery_beat:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    image: django_celery_beat
    command: /start-celerybeat
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.django
      - ./.envs/.postgres
    depends_on:
      - redis
      - postgres

  celery_flower:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    image: django_celery_flower
    command: /start-flower
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.django
      - ./.envs/.postgres
    ports:
      - "5555:5555"
    depends_on:
      - redis
      - postgres
