# Generated by Django 5.0.1 on 2024-01-07 15:12

import apps.utils.custome_models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=apps.utils.custome_models.ListField(blank=True, null=True),
        ),
    ]
