# Generated by Django 4.2.7 on 2024-01-30 16:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0007_rename_author_post_user"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="post",
            managers=[],
        ),
        migrations.AlterField(
            model_name="post",
            name="status",
            field=models.CharField(
                choices=[("draft", "Draft"), ("published", "Published"), ("archived", "Archived")],
                default="published",
                max_length=10,
            ),
        ),
    ]
